### ISSUE TITLE
libvips.so.42: undefined symbol

### ISSUE THREAD

**Issue by KishCom** [SecretAgentKen/deckxstream#7]
**Describe the bug**
Deckxstream will no longer load with the error:

```
deckxstream/node_modules/sharp/lib/sharp.js:34
  throw new Error(help.join('\n'));
  ^

Error: 
Something went wrong installing the "sharp" module

/usr/lib/libvips.so.42: undefined symbol: rsvg_handle_get_intrinsic_size_in_pixels

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/home/user/.asdf/installs/nodejs/18.14.2/lib/node_modules/deckxstream/node_modules/sharp/lib/sharp.js:34:9)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/user/.asdf/installs/nodejs/18.14.2/lib/node_modules/deckxstream/node_modules/sharp/lib/constructor.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

Node.js v18.14.2

```

**Specify your environment**
- OS: Arch Linux
- NodeJS Version: v18.14.2
- NPM Version: [...]
- Stream Deck Model: Standard
- Configuration File: N/A

**To Reproduce**
1. Install deckxstream on an updated Arch Linux system
2. Try to launch deckxstream
3. See error

-- 

I have tried to reinstall the `sharp` package as suggested by the error. It seems to install just fine but the error persists. `libvips` was recently updated to 8.14.1-1 and I wonder if that's part of the problem.

**Comment by KishCom** [comment]
This appears to have been due to a conflicting version of `libvips` on my machine. For anyone facing the same issue, fully remove libvips from your system, reinstall it (if required), and make sure the deckxstream is using the built in libvips library and not your systems.
